feat(bucket): patch endpoint for bucket data
spica-engine/spica pull request #481
Opened 2020-11-02 15:50 UTC by htuna07

2020-11-06 07:11 UTC, thesayyn requested changes

2020-11-06 07:19 UTC, htuna07 commented on stacks/api/bucket/src/bucket-data.controller.ts
> +    }
MongoDB will throw an error if the update query is empty, so we should detect this case but I could not decide what to do. Another option is returning the current document without performing an update operation in this case. Do you think the second option is a better choice?

2020-11-06 07:22 UTC, thesayyn commented on stacks/api/bucket/src/bucket-data.controller.ts
> +    }
Yes. it makes much more sense. I'd rather return an HTTP status code that indicates that the operation was successful but there were no updates.

2020-11-10 07:44 UTC, thesayyn approved these changes

2020-11-10 13:32 UTC, thesayyn approved these changes

2020-11-10 13:35 UTC, merged