style:(layout) function section has been merged with developer area
spica-engine/spica pull request #489
Opened 2020-11-05 12:15 UTC by akhnos

2020-11-06 07:10 UTC, thesayyn requested changes

2020-11-06 07:10 UTC, thesayyn commented on stacks/spica/packages/core/layout/home/home.layout.spec.ts
> +fdescribe("Home Layout", () => {
```suggestion
describe("Home Layout", () => {
```

2020-11-06 07:10 UTC, thesayyn commented on stacks/spica/packages/core/layout/home/home.layout.ts
> +        sub: {name: RouteCategory.Content_Sub, icon: "format_list_numbered"}
```suggestion
        children: {name: RouteCategory.Content_Sub, icon: "format_list_numbered"}
```

2020-11-06 07:10 UTC, thesayyn commented on stacks/spica/packages/core/layout/home/home.layout.ts
> +              )
```suggestion
              children: {
                    items: routes.filter(route => route.category == category.sub.name),
                    icon: category.sub.icon
               },
```

2020-11-06 07:10 UTC, thesayyn commented on stacks/spica/packages/core/route/route.ts
> +  System_Sub = "IAM Settings"
```suggestion
  System_Sub = "IA Management"
```

2020-11-10 08:13 UTC, akhnos commented
Change requests accepted

2020-11-20 09:07 UTC, thesayyn submitted a review, later dismissed

2020-11-23 09:19 UTC, htuna07 approved these changes

2020-11-23 09:20 UTC, merged