feat(bucket): unique field option
spica-engine/spica pull request #506
Opened 2020-11-19 15:31 UTC by htuna07

2020-11-20 09:22 UTC, thesayyn commented
Can we hold this PR until we land bucket rules? @htuna07.

There will be enormous conflicts between these PRs.

2020-12-10 15:38 UTC, thesayyn requested changes

2020-12-10 15:38 UTC, thesayyn commented on stacks/api/bucket/services/bucket.service.ts
> +    const bucketCollection = await this.db.createCollection(`bucket_${insertedBucket._id}`);
You can use getBucketDataCollection  from "@spica-server/bucket/services"

2020-12-10 15:38 UTC, thesayyn commented on stacks/api/bucket/services/bucket.service.ts
> +    const insertedBucket = await this.buckets.insertOne(bucket).then(t => t.ops[0]);
Also, you could use  super.insertOne().

2020-12-10 15:38 UTC, thesayyn commented on stacks/api/bucket/src/crud.ts
> +  return collection.insertOne(document).catch(error => {
You could return a message like `value of the property .title should unique across all documents.`

2020-12-10 15:38 UTC, thesayyn commented on stacks/api/bucket/src/crud.ts
> +        throw new BadRequestException(
Same as above.

2020-12-10 15:38 UTC, thesayyn commented on stacks/api/bucket/src/crud.ts
> +    .catch(error => {
same as above

2020-12-10 15:38 UTC, thesayyn commented
you should wait for the https://github.com/spica-engine/spica/pull/521 first.

2020-12-15 10:21 UTC, thesayyn commented
ping @htuna07

2021-01-04 10:27 UTC, akhnos approved these changes

2021-01-04 11:12 UTC, thesayyn approved these changes
lgtm

2021-01-04 11:15 UTC, merged