feat(bucket): full sized storage image preview on bucket-data edit page
spica-engine/spica pull request #915
Opened 2022-12-06 09:26 UTC by Davuttrg

2022-12-14 12:40 UTC, akhnos approved these changes

2022-12-15 08:13 UTC, htuna07 requested changes
Previewing existing storage objects of bucket-data and previewing after drag-drop works fine, but when I try to click the edit button, select another storage object, then click to preview before clicking the save button, the "Could not load the object" error is occurring.

2022-12-16 10:50 UTC, htuna07 commented on stacks/spica/src/storage/components/storage/storage.component.ts
> +    console.log("obj :", obj);
We should remove this line before merging the PR.

2022-12-16 10:54 UTC, htuna07 approved these changes

2022-12-16 12:35 UTC, merged